baseURL: 'https://boapps.hu/'
copyright: "Minden tartalom CC0 licensz alatt érhető el, kivéve, ha másképp van jelezve."
title: 'boa személyes oldala'
theme: 'govukhugo'
paginate: 5
enableInlineShortcodes: true
mainSections: ["posts", "joy", "sad"]
defaultContentLanguage: "hu"
languageCode: hu

outputs:
  home:
    - HTML
    - RSS
    - JSON

canonifyurls: true

pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2


params:
  govuk: false
  logo: none
  product: "boapps"
  builtby: boa
  builtbyurl: https://boapps.hu/

